/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.baka.tx.laundry.app;

import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import org.baka.tx.laundry.app.lib.database;
import org.baka.tx.laundry.app.model.admin;
import org.baka.tx.laundry.app.model.customer;

/**
 *
 * @author Tholut Akhyar
 */
public class CustomerEdit extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    database db;
    customer customer;
    admin admin;
    
    public CustomerEdit() {
        initComponents();
        this.setLocationRelativeTo(null);
        db = new database();
    }
    
    private void closeThisFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
    
    public void setAdmin(admin admin) {
        this.admin = admin;
    }
    
    public void setForm(String id, String nama, String alamat, String kontak) {
        customer = new customer(Integer.parseInt(id), nama, alamat, kontak);
        fieldCustomerID.setText(String.valueOf(customer.getId()));
        fieldCustomerNama.setText(customer.getNama());
        fieldCustomerAlamat.setText(customer.getAlamat());
        fieldCustomerKontak.setText(customer.getKontak());
    }

    private void doSimpanCustomer() {
        if (!customer.isFilled()) {
            JOptionPane.showMessageDialog(this, "Tolong isi Detail Customer", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (this.db.updateCustomer(customer)) {
            closeThisFrame();
        } else {
            JOptionPane.showMessageDialog(this, "Maaf Ada sedikit gangguan, Silahkan Ulangi Lagi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        fieldCustomerNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldCustomerAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldCustomerKontak = new javax.swing.JTextField();
        buttonDelete = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        fieldCustomerID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laundry Sanjaya - Ubah Order");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Ubah Customer");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        fieldCustomerNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldCustomerNamaKeyTyped(evt);
            }
        });

        jLabel3.setText("Nama");

        fieldCustomerAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerAlamatKeyReleased(evt);
            }
        });

        jLabel4.setText("Alamat");

        jLabel5.setText("Kontak");

        fieldCustomerKontak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerKontakKeyReleased(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(255, 204, 204));
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(204, 204, 0));
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        fieldCustomerID.setEditable(false);
        fieldCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldCustomerIDKeyTyped(evt);
            }
        });

        jLabel6.setText("Customer ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(fieldCustomerID))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(buttonBatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                .addComponent(fieldCustomerNama, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fieldCustomerAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fieldCustomerKontak, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCustomerNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCustomerAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCustomerKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBatal)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        doSimpanCustomer();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        if (this.db.deleteCustomer(String.valueOf(customer.getId()))) {
            closeThisFrame();
        } else {
            JOptionPane.showMessageDialog(this, "Maaf Ada sedikit gangguan, Silahkan Ulangi Lagi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void fieldCustomerNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerNamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerNamaKeyTyped

    private void fieldCustomerAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerAlamatKeyReleased
        // TODO add your handling code here:
        customer.setAlamat(fieldCustomerAlamat.getText());
    }//GEN-LAST:event_fieldCustomerAlamatKeyReleased

    private void fieldCustomerKontakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerKontakKeyReleased
        // TODO add your handling code here:
        customer.setKontak(fieldCustomerKontak.getText());
    }//GEN-LAST:event_fieldCustomerKontakKeyReleased

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        this.closeThisFrame();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void fieldCustomerNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerNamaKeyReleased
        // TODO add your handling code here:
        customer.setNama(fieldCustomerNama.getText());
    }//GEN-LAST:event_fieldCustomerNamaKeyReleased

    private void fieldCustomerIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerIDKeyReleased

    private void fieldCustomerIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JTextField fieldCustomerAlamat;
    private javax.swing.JTextField fieldCustomerID;
    private javax.swing.JTextField fieldCustomerKontak;
    private javax.swing.JTextField fieldCustomerNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
