/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.baka.tx.laundry.app;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import org.baka.tx.laundry.app.lib.database;
import org.baka.tx.laundry.app.model.admin;
import org.baka.tx.laundry.app.model.customer;
import org.baka.tx.laundry.app.model.order;

/**
 *
 * @author Tholut Akhyar
 */
public class OrderAdd extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    database db;
    order order;
    admin admin;
    
    public OrderAdd() {
        initComponents();
        this.setLocationRelativeTo(null);
        db = new database();
    }
    
    public void setAdmin(admin admin) {
        this.admin = admin;
    }
    
    private void closeThisFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));;
        this.resetForm();
    }
    
    public void resetForm() {
        order = new order();
        order.setAdmin(admin);
        cbJenisCucian.setSelectedIndex(0);
        String jenis = cbJenisCucian.getSelectedItem().toString();
        order.setJenis(jenis);
        fieldCustomerId.setText(null);
        fieldCustomerNama.setText(null);
        fieldCustomerAlamat.setText(null);
        fieldCustomerKontak.setText(null);
        fieldHargaPerKg.setText("0");
        fieldTotalBerat.setText("0");
        fieldCustomerPay.setText("0");
        fieldHargaPay.setText("0");
        fieldCustomerPayChange.setText("0");
        dateMulai.setDate(null);
        dateSelesai.setDate(null);
        this.showPerKgPrice();
    }
    
    private void showPerKgPrice() {
        fieldHargaPerKg.setText(String.valueOf(order.getHargaPerKg()));
    }
    
    private void calculateOrder() {
        this.showPerKgPrice();
        fieldHargaPay.setText(String.valueOf(order.getTotalHarga()));
        fieldCustomerPayChange.setText(String.valueOf(order.getJumlahKembalian()));
    }
    
    private void doTambahOrder() {
        if (order.getTglMulai() == null) {
            JOptionPane.showMessageDialog(this, "Tolong isi Tgl Mulai!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (order.getTglSelesai() == null) {
            JOptionPane.showMessageDialog(this, "Tolong isi Tgl Selesai!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!order.customer().isFilled()) {
            JOptionPane.showMessageDialog(this, "Tolong isi Detail Customer", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (order.getTotalBerat() <= 0) {
            JOptionPane.showMessageDialog(this, "Tolong isi Total Kilo Dengan Benar", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!order.isKembalianCorrect()) {
            JOptionPane.showMessageDialog(this, "Maaf Uang pembayaran Kurang!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (this.db.addOrder(order)) {
            closeThisFrame();
        } else {
            JOptionPane.showMessageDialog(this, "Maaf Ada sedikit gangguan, Silahkan Ulangi Lagi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        fieldCustomerId = new javax.swing.JTextField();
        fieldCustomerNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldCustomerAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldCustomerKontak = new javax.swing.JTextField();
        buttonPilihCustomer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fieldTotalBerat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateSelesai = new com.toedter.calendar.JDateChooser();
        dateMulai = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cbJenisCucian = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbDiantar = new javax.swing.JCheckBox();
        fieldHargaPay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldCustomerPay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldCustomerPayChange = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        fieldHargaPerKg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        buttonBatalPilihCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laundry Sanjaya - Tambah Order");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Order");

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        fieldCustomerId.setEditable(false);
        fieldCustomerId.setForeground(new java.awt.Color(153, 153, 153));
        fieldCustomerId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerIdKeyReleased(evt);
            }
        });

        fieldCustomerNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldCustomerNamaKeyTyped(evt);
            }
        });

        jLabel2.setText("Customer Id");

        jLabel3.setText("Nama");

        fieldCustomerAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerAlamatKeyReleased(evt);
            }
        });

        jLabel4.setText("Alamat");

        jLabel5.setText("Kontak");

        fieldCustomerKontak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerKontakKeyReleased(evt);
            }
        });

        buttonPilihCustomer.setText("Pilih");
        buttonPilihCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPilihCustomerActionPerformed(evt);
            }
        });

        jLabel6.setText("Tgl Mulai");

        fieldTotalBerat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fieldTotalBeratInputMethodTextChanged(evt);
            }
        });
        fieldTotalBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldTotalBeratKeyReleased(evt);
            }
        });

        jLabel7.setText("Total Berat (Kg)");

        dateSelesai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateSelesaiPropertyChange(evt);
            }
        });

        dateMulai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateMulaiPropertyChange(evt);
            }
        });

        jLabel8.setText("Tgl Selesai");

        cbJenisCucian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuci Biasa", "Cuci + Strika", "Cuci Kilat", "Cuci Boneka", "Cuci Selimut", "Cuci Mobil" }));
        cbJenisCucian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJenisCucianItemStateChanged(evt);
            }
        });

        jLabel9.setText("Jenis");

        cbDiantar.setText("Diantar?");

        fieldHargaPay.setEditable(false);
        fieldHargaPay.setForeground(new java.awt.Color(153, 153, 153));

        jLabel10.setText("Harga Yang Harus Dibayar");

        fieldCustomerPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerPayKeyReleased(evt);
            }
        });

        jLabel11.setText("Customer Membayar Sejumlah");

        fieldCustomerPayChange.setEditable(false);
        fieldCustomerPayChange.setForeground(new java.awt.Color(153, 153, 153));

        jLabel12.setText("Kembalian Untuk Customer");

        buttonCancel.setBackground(new java.awt.Color(255, 204, 204));
        buttonCancel.setText("Batal");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        fieldHargaPerKg.setEditable(false);
        fieldHargaPerKg.setForeground(new java.awt.Color(153, 153, 153));

        jLabel13.setText("Harga Per Kg");

        buttonBatalPilihCustomer.setText("Batal");
        buttonBatalPilihCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalPilihCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldHargaPay, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCustomerAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCustomerKontak, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPilihCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonBatalPilihCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldCustomerNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCustomerPay, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(fieldTotalBerat)
                            .addComponent(dateSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(dateMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbJenisCucian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbDiantar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(fieldCustomerPayChange)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(fieldHargaPerKg))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fieldCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonPilihCustomer)
                                            .addComponent(buttonBatalPilihCustomer)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldCustomerNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCustomerAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJenisCucian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDiantar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCustomerKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldTotalBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldHargaPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldHargaPerKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCustomerPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCustomerPayChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(buttonTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCancel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        doTambahOrder();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonPilihCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPilihCustomerActionPerformed
        // TODO add your handling code here:
        OrderSelectCustomer osc = new OrderSelectCustomer();
        osc.setAlwaysOnTop(true);
        osc.setLocationRelativeTo(null);
        osc.setAdmin(admin);
        osc.setVisible(true);
        osc.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                OrderSelectCustomer OrderSelectCustomerFrame = (OrderSelectCustomer) e.getWindow();
                if (OrderSelectCustomerFrame.selectedId > 0) {
                    customer cm = db.getCustomer(String.valueOf(OrderSelectCustomerFrame.selectedId));
                    order.setCustomer(cm);
                    fieldCustomerId.setText(String.valueOf(cm.getId()));
                    fieldCustomerNama.setText(cm.getNama());
                    fieldCustomerAlamat.setText(cm.getAlamat());
                    fieldCustomerKontak.setText(cm.getKontak());
                }
            }
        });
    }//GEN-LAST:event_buttonPilihCustomerActionPerformed

    private void fieldTotalBeratInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fieldTotalBeratInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalBeratInputMethodTextChanged

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        closeThisFrame();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void fieldTotalBeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTotalBeratKeyReleased
        // TODO add your handling code here:
        try {
            order.setTotalBerat(Integer.parseInt(fieldTotalBerat.getText()));
        } catch (NumberFormatException e) {
            order.setTotalBerat(0);
        }
        this.calculateOrder();
    }//GEN-LAST:event_fieldTotalBeratKeyReleased

    private void fieldCustomerPayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerPayKeyReleased
        // TODO add your handling code here:
        try {
            order.setJumlahDibayar(Integer.parseInt(fieldCustomerPay.getText()));
        } catch (NumberFormatException e) {
            order.setJumlahDibayar(0);
        }
        this.calculateOrder();
    }//GEN-LAST:event_fieldCustomerPayKeyReleased

    private void cbJenisCucianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJenisCucianItemStateChanged
        // TODO add your handling code here:
        order.setJenis(cbJenisCucian.getSelectedItem().toString());
        this.calculateOrder();
    }//GEN-LAST:event_cbJenisCucianItemStateChanged

    private void fieldCustomerNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerNamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerNamaKeyTyped

    private void fieldCustomerAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerAlamatKeyReleased
        // TODO add your handling code here:
        order.customer().setAlamat(fieldCustomerAlamat.getText());
    }//GEN-LAST:event_fieldCustomerAlamatKeyReleased

    private void fieldCustomerKontakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerKontakKeyReleased
        // TODO add your handling code here:
        order.customer().setKontak(fieldCustomerKontak.getText());
    }//GEN-LAST:event_fieldCustomerKontakKeyReleased

    private void fieldCustomerIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerIdKeyReleased
        // TODO add your handling code here:
        try {
            order.customer().setId(Integer.parseInt(fieldCustomerPay.getText()));
        } catch (NumberFormatException e) {
            order.customer().setId(0);
        }
    }//GEN-LAST:event_fieldCustomerIdKeyReleased

    private void dateMulaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateMulaiPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            try {
                order.setTglMulai((Date) evt.getNewValue());
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_dateMulaiPropertyChange

    private void dateSelesaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateSelesaiPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            try {
                order.setTglSelesai((Date) evt.getNewValue());
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_dateSelesaiPropertyChange

    private void fieldCustomerNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerNamaKeyReleased
        // TODO add your handling code here:
        order.customer().setNama(fieldCustomerNama.getText());
    }//GEN-LAST:event_fieldCustomerNamaKeyReleased

    private void buttonBatalPilihCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalPilihCustomerActionPerformed
        // TODO add your handling code here:
        order.setCustomer(new customer(0, "", "", ""));
        fieldCustomerId.setText("0");
        fieldCustomerNama.setText(order.customer().getNama());
        fieldCustomerAlamat.setText(order.customer().getAlamat());
        fieldCustomerKontak.setText(order.customer().getKontak());
    }//GEN-LAST:event_buttonBatalPilihCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatalPilihCustomer;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonPilihCustomer;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JCheckBox cbDiantar;
    private javax.swing.JComboBox<String> cbJenisCucian;
    private com.toedter.calendar.JDateChooser dateMulai;
    private com.toedter.calendar.JDateChooser dateSelesai;
    private javax.swing.JTextField fieldCustomerAlamat;
    private javax.swing.JTextField fieldCustomerId;
    private javax.swing.JTextField fieldCustomerKontak;
    private javax.swing.JTextField fieldCustomerNama;
    private javax.swing.JTextField fieldCustomerPay;
    private javax.swing.JTextField fieldCustomerPayChange;
    private javax.swing.JTextField fieldHargaPay;
    private javax.swing.JTextField fieldHargaPerKg;
    private javax.swing.JTextField fieldTotalBerat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
