/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.baka.tx.laundry.app;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import org.baka.tx.laundry.app.lib.database;
import org.baka.tx.laundry.app.model.admin;
import org.baka.tx.laundry.app.model.customer;
import org.baka.tx.laundry.app.model.order;

/**
 *
 * @author Tholut Akhyar
 */
public class OrderAction extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    database db;
    order order;
    admin admin;

    public OrderAction() {
        initComponents();
        this.setLocationRelativeTo(null);
        db = new database();
    }

    public void setAdmin(admin admin) {
        this.admin = admin;
    }

    private void closeThisFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    public void setForm(order order) {
        fieldCustomerId.setText(String.valueOf(order.customer().getId()));
        fieldCustomerNama.setText(order.customer().getNama());
        fieldCustomerAlamat.setText(order.customer().getAlamat());
        fieldCustomerKontak.setText(order.customer().getKontak());
        fieldHargaPerKg.setText(String.valueOf(order.getHargaPerKg()));
        fieldTotalBerat.setText(String.valueOf(order.getTotalBerat()));
        fieldCustomerPay.setText(String.valueOf(order.getJumlahDibayar()));
        fieldHargaPay.setText(String.valueOf(order.getTotalHarga()));
        fieldCustomerPayChange.setText(String.valueOf(order.getJumlahKembalian()));
        fieldTglMulai.setText(order.getTglMulai().toString());
        fieldTglSelesai.setText(order.getTglSelesai().toString());
        fieldJenis.setText(order.getJenis());
        fieldApakahDiantar.setText("Tidak");
        if (order.apakahDiantar()) {
            fieldApakahDiantar.setText("Ya");
        }

        if ("antri".equals(order.getStatus())) {
            cbStatus.setSelectedIndex(0);
        } else if ("proses".equals(order.getStatus())) {
            cbStatus.setSelectedIndex(1);
        } else if ("diantar".equals(order.getStatus())) {
            cbStatus.setSelectedIndex(2);
        } else if ("selesai".equals(order.getStatus())) {
            cbStatus.setSelectedIndex(3);
        }

        this.order = order;
    }

    private void doUpdateStatusOrder() {
        System.out.println(order.getStatus());
        if ("selesai".equals(order.getStatus())) {
            JOptionPane.showMessageDialog(this, "Maaf Pesanan Sudah Selesai, Status Tidak Dapat Diubah lagi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (this.db.updateStatusOrder(String.valueOf(order.getId()), cbStatus.getSelectedItem().toString().toLowerCase())) {
            closeThisFrame();
        } else {
            JOptionPane.showMessageDialog(this, "Maaf Ada sedikit gangguan, Silahkan Ulangi Lagi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonPerbaruiStatus = new javax.swing.JButton();
        fieldCustomerId = new javax.swing.JTextField();
        fieldCustomerNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldCustomerAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldCustomerKontak = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldTotalBerat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldCustomerPay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldCustomerPayChange = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        fieldHargaPerKg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldJenis = new javax.swing.JTextField();
        fieldTglMulai = new javax.swing.JTextField();
        fieldTglSelesai = new javax.swing.JTextField();
        fieldApakahDiantar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fieldHargaPay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laundry Sanjaya - Tambah Order");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Order No: 666");

        buttonPerbaruiStatus.setText("Perbarui Status");
        buttonPerbaruiStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerbaruiStatusActionPerformed(evt);
            }
        });

        fieldCustomerId.setEditable(false);
        fieldCustomerId.setForeground(new java.awt.Color(153, 153, 153));
        fieldCustomerId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerIdKeyReleased(evt);
            }
        });

        fieldCustomerNama.setEditable(false);
        fieldCustomerNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldCustomerNamaKeyTyped(evt);
            }
        });

        jLabel2.setText("Customer Id");

        jLabel3.setText("Nama");

        fieldCustomerAlamat.setEditable(false);
        fieldCustomerAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerAlamatKeyReleased(evt);
            }
        });

        jLabel4.setText("Alamat");

        jLabel5.setText("Kontak");

        fieldCustomerKontak.setEditable(false);
        fieldCustomerKontak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerKontakKeyReleased(evt);
            }
        });

        jLabel6.setText("Tgl Mulai");

        fieldTotalBerat.setEditable(false);
        fieldTotalBerat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fieldTotalBeratInputMethodTextChanged(evt);
            }
        });
        fieldTotalBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldTotalBeratKeyReleased(evt);
            }
        });

        jLabel7.setText("Total Berat (Kg)");

        jLabel8.setText("Tgl Selesai");

        jLabel9.setText("Jenis");

        fieldCustomerPay.setEditable(false);
        fieldCustomerPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCustomerPayKeyReleased(evt);
            }
        });

        jLabel11.setText("Customer Membayar Sejumlah");

        fieldCustomerPayChange.setEditable(false);
        fieldCustomerPayChange.setForeground(new java.awt.Color(153, 153, 153));

        jLabel12.setText("Kembalian Untuk Customer");

        buttonCancel.setBackground(new java.awt.Color(255, 204, 204));
        buttonCancel.setText("Tutup");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        fieldHargaPerKg.setEditable(false);
        fieldHargaPerKg.setForeground(new java.awt.Color(153, 153, 153));

        jLabel13.setText("Harga Per Kg");

        fieldJenis.setEditable(false);
        fieldJenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldJenisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldJenisKeyTyped(evt);
            }
        });

        fieldTglMulai.setEditable(false);
        fieldTglMulai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldTglMulaiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldTglMulaiKeyTyped(evt);
            }
        });

        fieldTglSelesai.setEditable(false);
        fieldTglSelesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldTglSelesaiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldTglSelesaiKeyTyped(evt);
            }
        });

        fieldApakahDiantar.setEditable(false);
        fieldApakahDiantar.setText("Tidak");
        fieldApakahDiantar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldApakahDiantarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldApakahDiantarKeyTyped(evt);
            }
        });

        jLabel14.setText("Di Antar?");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antri", "Proses", "Diantar", "Selesai" }));

        jLabel15.setText("Status");

        jLabel10.setText("Harga Yang Harus Dibayar");

        fieldHargaPay.setEditable(false);
        fieldHargaPay.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPerbaruiStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldCustomerAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldCustomerKontak, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldCustomerNama, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(fieldCustomerId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldTglMulai)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(fieldJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(fieldApakahDiantar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fieldTglSelesai)
                            .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(fieldTotalBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldHargaPerKg)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(0, 34, Short.MAX_VALUE))))
                        .addComponent(fieldCustomerPay)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(fieldCustomerPayChange)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldHargaPay))
                    .addComponent(jLabel10))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fieldCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldTglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(29, 29, 29))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldTotalBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCustomerNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldTglSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldHargaPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldHargaPerKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCustomerPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCustomerAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldApakahDiantar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCustomerKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCustomerPayChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPerbaruiStatus)
                    .addComponent(buttonCancel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPerbaruiStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerbaruiStatusActionPerformed
        // TODO add your handling code here:
        doUpdateStatusOrder();
    }//GEN-LAST:event_buttonPerbaruiStatusActionPerformed

    private void fieldTotalBeratInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fieldTotalBeratInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalBeratInputMethodTextChanged

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        closeThisFrame();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void fieldTotalBeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTotalBeratKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalBeratKeyReleased

    private void fieldCustomerPayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerPayKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerPayKeyReleased

    private void fieldCustomerNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerNamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerNamaKeyTyped

    private void fieldCustomerAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerAlamatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerAlamatKeyReleased

    private void fieldCustomerKontakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerKontakKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerKontakKeyReleased

    private void fieldCustomerIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerIdKeyReleased

    private void fieldCustomerNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCustomerNamaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerNamaKeyReleased

    private void fieldJenisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldJenisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJenisKeyReleased

    private void fieldJenisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldJenisKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJenisKeyTyped

    private void fieldTglMulaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTglMulaiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTglMulaiKeyReleased

    private void fieldTglMulaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTglMulaiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTglMulaiKeyTyped

    private void fieldTglSelesaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTglSelesaiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTglSelesaiKeyReleased

    private void fieldTglSelesaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTglSelesaiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTglSelesaiKeyTyped

    private void fieldApakahDiantarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldApakahDiantarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApakahDiantarKeyReleased

    private void fieldApakahDiantarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldApakahDiantarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApakahDiantarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderAction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonPerbaruiStatus;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JTextField fieldApakahDiantar;
    private javax.swing.JTextField fieldCustomerAlamat;
    private javax.swing.JTextField fieldCustomerId;
    private javax.swing.JTextField fieldCustomerKontak;
    private javax.swing.JTextField fieldCustomerNama;
    private javax.swing.JTextField fieldCustomerPay;
    private javax.swing.JTextField fieldCustomerPayChange;
    private javax.swing.JTextField fieldHargaPay;
    private javax.swing.JTextField fieldHargaPerKg;
    private javax.swing.JTextField fieldJenis;
    private javax.swing.JTextField fieldTglMulai;
    private javax.swing.JTextField fieldTglSelesai;
    private javax.swing.JTextField fieldTotalBerat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
